In [16]:
import numpy as np
X=np.array([[1,2,3,5],[2,3,4,5],[1,1,1,6],[1,2,3,5]])
print(X)
y=np.array([1,2,3,1])
print('/n',y)
X[np.arange(4),y]

[[1 2 3 5]
 [2 3 4 5]
 [1 1 1 6]
 [1 2 3 5]]
/n [1 2 3 1]


array([2, 4, 6, 2])

In [93]:
import numpy as np
matrix=np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])

print(matrix)
length = len(matrix)-1;
length1=length/2
   
for i in np.arange(0,int(length1),1): 
    for j in np.arange(i,length-i,1):
        
        p1 = matrix[i][j];
        p2 = matrix[j][length-i];
        p3 = matrix[length-i][length-j];
        p4 = matrix[length-j][i];

        matrix[j][length-i] = p1;
        matrix[length-i][length-j] = p2;
        matrix[length-j][i] = p3;
        matrix[i][j] = p4;

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 4 1]
 [8 5 2]
 [9 6 3]]
